### ISSUE TITLE
auto-assignee test

### ISSUE THREAD

**Issue by ghost** [klokantech/test#19]
<p>FROM:<a href="mailto:sysadmin@klokantech.com">sysadmin@klokantech.com</a>	KlokanTech SysAdmin<br>
CC:info@oldrichvykydal.cz,o.vykydal@gmail.com<br>
test</p>
<p>Link to the Clientportal:<br>
<a href="https://clientportal.klokantech.com/test/issues/19">https://clientportal.klokantech.com/test/issues/19</a></p>

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal
test

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal
test

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal
test

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal
test

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal

**Comment by ghost** [comment]
FROM:o.vykydal@gmail.com	olda
test

**Comment by ghost** [comment]
FROM:info@oldrichvykydal.cz	Oldřich Vykydal
test

**Comment by o1da** [comment]
test
